# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='amazon_web.MyUser'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_num',
            field=models.CharField(default='Not Ready', max_length=50),
        ),
    ]
