# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
