# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_web', '0002_auto_20170421_1844'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='order',
            new_name='orders',
        ),
    ]
