# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_web', '0003_auto_20170421_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='count',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
