# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_web', '0005_orders_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='address_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myuser',
            name='address_y',
            field=models.IntegerField(default=0),
        ),
    ]
