# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_web', '0007_auto_20170429_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
    ]
