# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 02:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_web', '0008_orders_purchased'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='tracking_num',
            new_name='truck_id',
        ),
    ]
